apiVersion: v1
kind: Service
metadata:
  name: redis

spec:
  type: LoadBalancer
  selector:
    app: redis

  ports:
    - name: jwt
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: pubsub
      port: 6380
      targetPort: 6379
      protocol: TCP