apiVersion: apps/v1
kind: Deployment
metadata:
  name: friday-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: friday-demo
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: friday-demo
    spec:
      containers:
        - name: friday-demo
          image: ghcr.io/kwanok/friday-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 8080
